# Generated by Django 5.0.4 on 2024-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("braschuene", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
