# Generated by Django 5.0.4 on 2024-04-23 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("braschuene", "0002_debt_done"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debt",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="debt",
            name="sender",
        ),
        migrations.AddField(
            model_name="debt",
            name="receivers",
            field=models.ManyToManyField(
                related_name="debts_received", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="senders",
            field=models.ManyToManyField(
                related_name="debts_sent", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
