# Generated by Django 5.0.4 on 2024-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("braschuene", "0003_remove_debt_receiver_remove_debt_sender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debt",
            name="done",
        ),
        migrations.AddField(
            model_name="debt",
            name="paid_at",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
