# Generated by Django 5.0.4 on 2024-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("braschuene", "0004_remove_debt_done_debt_paid_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debt",
            name="paid_at",
        ),
        migrations.AddField(
            model_name="debt",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
