# Generated by Django 5.0.6 on 2024-06-18 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPlayersGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.PositiveSmallIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('ev_defensive', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ev_defensive', to=settings.AUTH_USER_MODEL)),
                ('ev_offensive', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ev_offensive', to=settings.AUTH_USER_MODEL)),
                ('sd_defensive', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sd_defensive', to=settings.AUTH_USER_MODEL)),
                ('sd_offensive', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sd_offensive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
