# Generated by Django 5.0.6 on 2024-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0002_alter_fourplayersgame_ev_defensive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourplayersgame',
            name='round_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='fourplayersgame',
            name='game_round',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
