# Generated by Django 5.0.6 on 2024-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0004_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_crate',
            field=models.BooleanField(default=False),
        ),
    ]
