# Generated by Django 5.0.6 on 2024-06-19 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0006_beer_is_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoPlayersGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.SmallIntegerField(default=-1)),
                ('round_name', models.CharField(default='', max_length=64)),
                ('finished', models.BooleanField(default=False)),
                ('ev_player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_player', to=settings.AUTH_USER_MODEL)),
                ('sd_player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sd_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
