# Generated by Django 5.0.6 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0008_threeplayersgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sicherungskasten',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
