# Generated by Django 5.0.6 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0009_profile_sicherungskasten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sicherungskasten',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bier im Sicherheitskasten'),
        ),
    ]
