# Generated by Django 5.0.6 on 2024-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0011_alter_profile_sicherungskasten'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourplayersgame',
            name='ev_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fourplayersgame',
            name='sd_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threeplayersgame',
            name='ev_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threeplayersgame',
            name='sd_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='ev_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twoplayersgame',
            name='sd_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sicherungskasten',
            field=models.SmallIntegerField(default=0, verbose_name='Bier im Sicherungskasten'),
        ),
    ]
