# Generated by Django 5.0.6 on 2024-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0012_fourplayersgame_ev_score_fourplayersgame_sd_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inside_tag_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Inside Tag ID'),
        ),
    ]
