# Generated by Django 5.0.6 on 2024-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0013_profile_inside_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inside_tag_id',
            field=models.CharField(blank=True, default='', help_text='ID des Inside Tags für die Anwesenheitserkennung und auto-log-out', max_length=64, verbose_name='Inside Tag ID'),
        ),
    ]
