# Generated by Django 5.0.7 on 2024-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0014_alter_profile_inside_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isGuest',
            field=models.BooleanField(default=False),
        ),
    ]
