# Generated by Django 5.0.7 on 2024-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braschüne', '0015_profile_isguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2264922221.jpg'),
        ),
    ]
